(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.org/packages/")
(source "melpa-stable" "http://stable.melpa.org/packages/")
(source org)

(files "init.el" "files/*.el" "site-lisp/*.el")

(depends-on "assess")
(depends-on "auctex")
(depends-on "buttercup")
(depends-on "cask")
(depends-on "concurrent")
(depends-on "czech-holidays")
(depends-on "deferred")
(depends-on "ibuffer-vc")
(depends-on "impatient-mode")
(depends-on "inf-mongo")
(depends-on "jdee")
(depends-on "jq-mode")
(depends-on "json-mode")
(depends-on "jump-char")
(depends-on "keyfreq")
(depends-on "ledger-mode")
(depends-on "legalese")
(depends-on "less-css-mode")
(depends-on "macrostep")
(depends-on "markdown-toc")
(depends-on "mocha")
(depends-on "nginx-mode")
(depends-on "notmuch")
(depends-on "nov")
(depends-on "nvm")
(depends-on "oauth2")
(depends-on "ob-async")
(depends-on "ob-elixir")
(depends-on "ob-mongo")
(depends-on "ob-restclient")
(depends-on "omnisharp")
(depends-on "org-make-toc")
(depends-on "org-noter")
(depends-on "outshine")
(depends-on "ov")
(depends-on "overseer")
(depends-on "package-lint")
(depends-on "pallet")
(depends-on "pandoc-mode")
(depends-on "paredit")
(depends-on "paren-face")
(depends-on "parse-csv")
(depends-on "password-generator")
(depends-on "pomidor")
(depends-on "poporg")
(depends-on "pos-tip")
(depends-on "projectile")
(depends-on "psysh")
(depends-on "puppet-mode")
(depends-on "rainbow-mode")
(depends-on "restclient")
(depends-on "rjsx-mode")
(depends-on "rust-mode")
(depends-on "scala-mode")
(depends-on "scf-mode")
(depends-on "shackle")
(depends-on "shell-pop")
(depends-on "smart-jump")
(depends-on "smartscan")
(depends-on "smex")
(depends-on "string-edit")
(depends-on "systemd")
(depends-on "textile-mode")
(depends-on "transpose-frame")
(depends-on "tuareg")
(depends-on "undercover")
(depends-on "undo-tree")
(depends-on "visual-regexp")
(depends-on "web-mode")
(depends-on "web-server")
(depends-on "wgrep-ag")
(depends-on "which-key")
(depends-on "world-time-mode")
(depends-on "yaml-mode")
(depends-on "yarn-mode")
(depends-on "yasnippet")

(development
 (depends-on "elsa")
 (depends-on "trinary"))
