(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.org/packages/")
(source "melpa-stable" "http://stable.melpa.org/packages/")
(source org)

(depends-on "auctex")
(depends-on "buttercup")
(depends-on "cask")
(depends-on "concurrent")
(depends-on "deferred")
(depends-on "ibuffer-vc")
(depends-on "impatient-mode")
(depends-on "jq-mode")
(depends-on "json-mode")
(depends-on "jump-char")
(depends-on "legalese")
(depends-on "less-css-mode")
(depends-on "macrostep")
(depends-on "notmuch")
(depends-on "oauth2")
(depends-on "overseer")
(depends-on "package-lint")
(depends-on "pallet")
(depends-on "parse-csv")
(depends-on "pomidor")
(depends-on "psysh")
(depends-on "rainbow-mode")
(depends-on "shell-pop")
(depends-on "smex")
(depends-on "visual-regexp")
(depends-on "web-mode")
